openapi: 3.0.3

info:
  title: DeliveryService API
  description: API to process home deliveries for ordered meals
  version: 1.0.0

servers:
  - url: http://127.0.0.1:8003
    description: URL for local development and testing
  - url: https://fictitious.com
    description: main production server
  - url: https://fictitious-staging.com
    description: staging server for testing purposes only

paths:
  /v1/deliveries:
    post:
      tags:
        - delivery
      summary: Dispatches a meal order for home delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryPayload'

      responses:
        '202':
          description: A JSON representation of the dispatched order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryResponse'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /health:
    get:
      description: '***Health check endpoint..***'
      summary: Health Check
      tags:
        - Health
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthSchema'

components:
  responses:
    UnprocessableEntity:
      description: The payload contains invalid values.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    OrderItemSchema:
      additionalProperties: false
      type: object
      required:
        - product
        - quantity
      properties:
        product:
          type: string
          enum:
            - Double Cheeseburger
            - Lasagna
            - Veil with glazed onions and blue cheese
            - Vegetarian Salad with healthy produce
        quantity:
          type: integer
          minimum: 1

    DeliveryPayload:
      type: object
      additionalProperties: false
      required:
        - items
        - metadata
        - address
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSchema'
        metadata:
          $ref: '#/components/schemas/MetadataSchema'
        address:
          $ref: '#/components/schemas/CustomerAddressSchema'

    DeliveryResponse:
      type: object
      additionalProperties: false
      required:
        - delivery_id
        - items
        - scheduled
        - status
        - metadata
      properties:
        delivery_id:
          type: string
          format: uuid
        scheduled:
          type: string
          format: 'date-time'
        status:
          type: string
          enum:
            - deliveryScheduled
            - driverAvailable
            - inTransit
            - delivered
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSchema'
        metadata:
          $ref: '#/components/schemas/MetadataSchema'

    MetadataSchema:
      type: object
      additionalProperties: false
      description: 'Representation of Order metadata in the system.'
      required:
        - receiver
        - order_id
        - customer_id
      properties:
        receiver:
          description: Requesting service.
          example: OrderService
          type: string
        order_id:
          description: Order ID of the Order currently being handled.
          example: b76d019f-5937-4a14-8091-1d9f18666c93
          type: string
        customer_id:
          description: Customer ID for the Order currently being handled.
          example: f2861560-e9ed-4463-955f-0c55c3b416fb
          type: string

    CustomerAddressSchema:
      type: object
      description: 'Representation of Customer Address Information in the system. '
      example:
        name: Barirah Chou
        street: Stallstigen 30
        zipcode: 111 21
        city: Stockholm
      required:
        - name
        - street
        - zipcode
        - city
      properties:
        name:
          type: string
        street:
          type: string
        zipcode:
          type: string
        city:
          type: string

    HealthSchema:
      type: object
      description: 'Representation of service Health status in the system. '
      example:
        status: true
        version: 1.0.0
        name: DeliveryService
      required:
        - status
        - version
        - name
      properties:
        status:
          type: boolean
        version:
          type: string
        name:
          type: string
